/**
 * Turning a canvas document into the same kind of HTML+CSS the fixed templates
 * produce, so it flows through the existing pipeline untouched: iframe preview
 * in the editor, and Cloudflare Browser Rendering for the PDF and PNG.
 *
 * Two things are deliberate:
 *
 *  - **Styles go in a stylesheet keyed by element index, not in `style=`
 *    attributes.** Values reach here from a JSONB column, and building an
 *    attribute out of them means every colour and font name is an injection
 *    site. Index-based class names are generated by us and contain nothing from
 *    the document.
 *  - **Escaping happens here and only here.** Bindings are substituted into the
 *    raw template first (see `substituteBindings`), so this is the single point
 *    where recipient data becomes markup. Escaping earlier would double-escape
 *    the design's own text; escaping later would not happen at all.
 */
import { escapeHtml } from '../templates/shared';
import type { CertificateRenderData } from '../types';
import { buildBindingValues, substituteBindings, type BindingValues } from './bindings';
import { fitText } from './fit';
import {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  type CertificateDocument,
  type CertificateElement,
  type HorizontalAlign,
  type ImageElement,
  type ShapeElement,
  type TextElement,
  type VerticalAlign
} from './types';

export interface DocumentRenderInput {
  document: CertificateDocument;
  data: CertificateRenderData;
  /** The client company's branding — the second mark on the certificate. */
  clientBrand?: { name?: string; logoUrl?: string };
  /** Swap real data for worst-case values; used by the editor's stress preview. */
  bindingOverrides?: BindingValues;
}

/**
 * Same `{ body, styles }` shape a `TemplateRenderer` returns, so `renderCertificate`
 * can wrap either one without caring which produced it.
 */
export interface DocumentRenderOutput {
  body: string;
  styles: string;
  /** Elements whose content did not fit, so the editor can flag them. */
  overflowingElementIds: string[];
}

const ALIGN_TO_FLEX: Record<HorizontalAlign, string> = {
  left: 'flex-start',
  center: 'center',
  right: 'flex-end'
};

const VERTICAL_TO_FLEX: Record<VerticalAlign, string> = {
  top: 'flex-start',
  middle: 'center',
  bottom: 'flex-end'
};

/**
 * Which generic family a face degrades to when its stylesheet has not arrived.
 *
 * Everything used to fall back to `Georgia, serif`, so a blocked or slow font
 * turned Space Grotesk into a serif and JetBrains Mono into a proportional one —
 * a different shape AND different metrics from what the fit engine measured,
 * which is how text ends up outside the box it was sized for. The fonts arrive
 * over the network, so this is a normal state, not an edge case.
 */
const FONT_CATEGORY: Record<string, string> = {
  'Cormorant Garamond': 'Georgia, serif',
  'Bodoni Moda': 'Georgia, serif',
  'Playfair Display': 'Georgia, serif',
  Cinzel: 'Georgia, serif',
  'Archivo Black': 'Arial Black, Helvetica, sans-serif',
  'Space Grotesk': 'Helvetica, Arial, sans-serif',
  'DM Mono': 'Consolas, monospace',
  'JetBrains Mono': 'Consolas, monospace'
};

/** `Cormorant Garamond` → `'Cormorant Garamond', Georgia, serif`. */
export function fontStack(family: string): string {
  const fallback = FONT_CATEGORY[family] ?? 'Georgia, serif';

  return `'${family.replace(/'/g, '')}', ${fallback}`;
}

function positionRules(element: CertificateElement): string[] {
  const rules = [
    'position: absolute',
    `left: ${element.x}px`,
    `top: ${element.y}px`,
    `width: ${element.w}px`,
    `height: ${element.h}px`
  ];

  if (element.rotation) {
    rules.push(`transform: rotate(${element.rotation}deg)`, 'transform-origin: center center');
  }

  if (typeof element.opacity === 'number' && element.opacity < 1) {
    rules.push(`opacity: ${Math.max(0, element.opacity)}`);
  }

  return rules;
}

function renderTextElement(
  element: TextElement,
  className: string,
  values: BindingValues
): { body: string; styles: string; overflowed: boolean } {
  const resolved = substituteBindings(element.content, values);
  const fit = fitText(element, resolved);
  const { style } = element;

  const outer = [
    ...positionRules(element),
    'display: flex',
    `align-items: ${VERTICAL_TO_FLEX[style.verticalAlign]}`,
    `justify-content: ${ALIGN_TO_FLEX[style.align]}`
  ];

  const inner = [
    'width: 100%',
    `font-family: ${fontStack(style.fontFamily)}`,
    `font-size: ${fit.fontSize}px`,
    `font-weight: ${style.fontWeight}`,
    `line-height: ${style.lineHeight}`,
    `letter-spacing: ${style.letterSpacing}px`,
    `color: ${style.color}`,
    `text-align: ${style.align}`,
    // Long unbroken strings are hard-wrapped rather than allowed to escape the
    // box, matching what the fit engine assumed when it counted lines.
    'overflow-wrap: break-word',
    'white-space: pre-wrap'
  ];

  if (style.italic) inner.push('font-style: italic');
  if (style.uppercase) inner.push('text-transform: uppercase');

  if (element.fit === 'clamp' && fit.maxLines) {
    // -webkit-box is what gives line-clamp; it has to sit on the INNER element,
    // which is why the vertical alignment lives on a separate outer flex box.
    inner.push(
      'display: -webkit-box',
      '-webkit-box-orient: vertical',
      `-webkit-line-clamp: ${fit.maxLines}`,
      'overflow: hidden'
    );
  }

  const body = `<div class="${className}"><div class="${className}-t">${escapeHtml(resolved)}</div></div>`;
  const styles = `.${className} { ${outer.join('; ')}; }\n.${className}-t { ${inner.join('; ')}; }`;

  return { body, styles, overflowed: fit.overflows };
}

function resolveImageUrl(element: ImageElement, input: DocumentRenderInput): string | undefined {
  switch (element.source.kind) {
    case 'orgLogo':
      return input.data.orgLogoUrl || undefined;
    case 'clientLogo':
      return input.clientBrand?.logoUrl || undefined;
    case 'upload':
      return element.source.url || undefined;
  }
}

function renderImageElement(
  element: ImageElement,
  className: string,
  input: DocumentRenderInput
): { body: string; styles: string } | null {
  const url = resolveImageUrl(element, input);

  // A course with no client logo should not print a broken-image icon on every
  // certificate it issues.
  if (!url) {
    return element.hideWhenEmpty === false ? { body: `<div class="${className}"></div>`, styles: `.${className} { ${positionRules(element).join('; ')}; }` } : null;
  }

  const outer = positionRules(element);
  const inner = [
    'width: 100%',
    'height: 100%',
    `object-fit: ${element.fit}`,
    'display: block'
  ];

  if (element.radius) inner.push(`border-radius: ${element.radius}px`);

  const body = `<div class="${className}"><img src="${escapeHtml(url)}" alt="" class="${className}-i"></div>`;
  const styles = `.${className} { ${outer.join('; ')}; }\n.${className}-i { ${inner.join('; ')}; }`;

  return { body, styles };
}

function renderShapeElement(element: ShapeElement, className: string): { body: string; styles: string } {
  const rules = positionRules(element);

  if (element.fill) rules.push(`background: ${element.fill}`);
  if (element.strokeWidth && element.strokeColor) {
    rules.push(`border: ${element.strokeWidth}px solid ${element.strokeColor}`);
  }

  if (element.shape === 'ellipse') {
    rules.push('border-radius: 50%');
  } else if (element.radius) {
    rules.push(`border-radius: ${element.radius}px`);
  }

  // A line is a rect collapsed to its stroke; giving it its own shape keeps the
  // editor's rules simple (a line resizes on one axis).
  if (element.shape === 'line') {
    rules.push(`height: ${Math.max(1, element.strokeWidth ?? 1)}px`);
    if (!element.fill) rules.push(`background: ${element.strokeColor ?? '#000000'}`);
  }

  return { body: `<div class="${className}"></div>`, styles: `.${className} { ${rules.join('; ')}; }` };
}

function canvasStyles(document: CertificateDocument): string {
  const { canvas } = document;
  const rules = [
    `width: ${CANVAS_WIDTH}px`,
    `height: ${CANVAS_HEIGHT}px`,
    'position: relative',
    'overflow: hidden',
    `background-color: ${canvas.color}`
  ];

  if (canvas.imageUrl) {
    rules.push(`background-image: url('${canvas.imageUrl.replace(/'/g, '')}')`, 'background-size: cover', 'background-position: center');
  }

  const borderRule =
    canvas.borderWidth && canvas.borderColor
      ? `.doc-border { position: absolute; inset: ${canvas.borderInset ?? 0}px; border: ${canvas.borderWidth}px solid ${canvas.borderColor}; pointer-events: none; }`
      : '';

  return `.cert.doc { ${rules.join('; ')}; }\n${borderRule}`;
}

/**
 * Render a document to the `{ html, styles }` pair the rest of the pipeline
 * already speaks, plus the ids of elements whose content did not fit.
 */
export function renderDocument(input: DocumentRenderInput): DocumentRenderOutput {
  const values = input.bindingOverrides ?? buildBindingValues(input.data, input.clientBrand?.name ?? '');

  const bodies: string[] = [];
  const styles: string[] = [canvasStyles(input.document)];
  const overflowingElementIds: string[] = [];

  input.document.elements.forEach((element, index) => {
    // Generated, not derived from the document: an id from the database must
    // never end up as part of a selector.
    const className = `el-${index}`;

    if (element.kind === 'text') {
      const rendered = renderTextElement(element, className, values);
      bodies.push(rendered.body);
      styles.push(rendered.styles);
      if (rendered.overflowed) overflowingElementIds.push(element.id);
      return;
    }

    if (element.kind === 'image') {
      const rendered = renderImageElement(element, className, input);
      if (rendered) {
        bodies.push(rendered.body);
        styles.push(rendered.styles);
      }
      return;
    }

    const rendered = renderShapeElement(element, className);
    bodies.push(rendered.body);
    styles.push(rendered.styles);
  });

  const border = input.document.canvas.borderWidth ? '<div class="doc-border"></div>' : '';

  return {
    body: `<div class="cert doc">${bodies.join('')}${border}</div>`,
    styles: styles.join('\n'),
    overflowingElementIds
  };
}
