import { z } from 'zod';

// ─── Agent Roles ─────────────────────────────────────────────────────────────

export const AgentRole = {
  TEACHER: 'teacher',
  STUDENT: 'student'
} as const;

export type AgentRole = (typeof AgentRole)[keyof typeof AgentRole];

// ─── AI Provider Configuration ───────────────────────────────────────────────

export const AIProvider = {
  OPENAI: 'openai',
  ANTHROPIC: 'anthropic',
  GOOGLE: 'google',
  MOONSHOT: 'moonshot',
  MINIMAX: 'minimax'
} as const;

export type AIProvider = (typeof AIProvider)[keyof typeof AIProvider];

export interface AIProviderConfig {
  provider: AIProvider;
  apiKey: string;
  model?: string;
}

// ─── Agent Context (passed with each chat message) ───────────────────────────

export interface AgentContext {
  orgId: string;
  courseId: string;
  courseTitle: string;
  courseDescription?: string;
  userId: string;
  role: AgentRole;
  locale: string;
  lessonId?: string;
  lessonTitle?: string;
  lessonContent?: string;
  exerciseId?: string;
  exerciseTitle?: string;
  documentId?: string;
  documentText?: string;
  /**
   * True when a document is attached but served via RAG (search_document) instead
   * of inline — edit/extend mode on an already-built course. The agent must call
   * search_document to read from it, since documentText is intentionally omitted.
   */
  searchableDocument?: boolean;
  /**
   * How many course sources ride in the separate "Course Sources" message that
   * precedes this context block.
   *
   * The material is NOT inlined here on purpose. This context block changes every
   * turn (course structure, plan progress), and a prompt cache is a prefix match —
   * embedding the sources in it meant the whole pack was re-written to the cache
   * on every build turn instead of being read back at a tenth of the price.
   */
  courseSourceCount?: number;
  /** Sources that had to be summarized because the pack budget ran out. */
  truncatedSourceCount?: number;
  /**
   * Las fuentes viajan como ÍNDICE (nombre, tamaño, cómo se leyó, de qué trata)
   * y no como texto: el contenido se pide con `read_source`.
   *
   * Cambia lo que hay que decirle al modelo. Con el paquete, la instrucción es
   * "el texto está más arriba, leelo ahí"; con el índice, "el texto no está,
   * pedilo". Decirle lo primero cuando es lo segundo es cómo un agente termina
   * afirmando que no puede ver un documento que sí tiene a mano — o peor,
   * escribiendo como si lo hubiera leído.
   */
  sourcesAsIndex?: boolean;
  existingSectionCount?: number;
}

// ─── Course Plan (generated by the agent in Plan Mode) ───────────────────────

export const CoursePlanItemSchema = z.object({
  type: z.enum(['lesson', 'exercise']).describe("'lesson' for content lessons, 'exercise' for quizzes/assessments"),
  title: z.string().min(1),
  description: z.string().min(1),
  order: z.number().int().min(0),
  hasExercise: z
    .boolean()
    .default(false)
    .describe('Only for lessons: whether to also create an exercise linked to this lesson'),
  /**
   * De qué fuente sale esta lección — declarado por el agente y contrastado por
   * el servidor contra las fuentes que el curso tiene de verdad.
   *
   * `.optional()` y NO `.default([])`, que es la diferencia que hace que esto
   * funcione. Con un valor por defecto, «no contestó la pregunta» y «contestó
   * que no hay ninguna» llegan al servidor como el mismo array vacío, y son
   * cosas opuestas: la primera se responde pidiéndole que declare, la segunda
   * hablando con el docente. Medido: la primera vez que se probó, el modelo
   * omitió el campo entero y el servidor reportó 14 lecciones huérfanas de 14,
   * incluidas las que el organigrama sí cubría.
   *
   * Opcional y no obligatorio porque un campo obligatorio que el modelo no
   * puede producir tira la llamada entera, y un plan es lo más caro que hay acá
   * para perder. Además, los planes aprobados antes de que el campo existiera
   * tienen que seguir parseando: si `getLatestImplementationPlan` deja de
   * reconocerlos, el ancla de progreso desaparece a mitad de una construcción.
   */
  sources: z
    .array(z.string())
    .optional()
    .describe(
      'REQUIRED on every lesson when the course has attached sources. The file name(s) from the "## Course Sources" list whose material actually carries this lesson. Send an EMPTY ARRAY when no attached source covers it — that is a truthful answer and the server surfaces it to the teacher. Never name a source that is not in that list.'
    ),
  /**
   * Qué se le hace a esta pieza. Ausente = `create`, que es lo que todo plan
   * anterior a los planes de cambios quería decir.
   *
   * Medido el 2026-09-21: «agregá una sección» devolvía el plan del curso
   * ENTERO, porque el esquema exigía examen final y el prompt pedía el plan
   * completo. El docente veía treinta ítems para revisar y aprobar cuando había
   * pedido uno. Con `action`, un plan puede hablar de lo que ya existe sin
   * fingir que se construye de nuevo.
   */
  action: z
    .enum(['create', 'rewrite', 'edit'])
    .optional()
    .describe(
      'What happens to this item. "create" (the default) builds it from scratch. "rewrite" writes an EXISTING lesson again from the material. "edit" changes specific facts inside an existing lesson or exercise, leaving the rest untouched. Only used in a change plan (scope "changes").'
    ),
  target: z
    .string()
    .optional()
    .describe(
      'The handle (e.g. S2.L3) or id of the EXISTING lesson/exercise this item acts on. Required for "rewrite" and "edit"; leave it out for "create".'
    ),
  changes: z
    .string()
    .optional()
    .describe(
      'What changes, in one or two sentences — the teacher reads this to decide. Required for "rewrite" and "edit".'
    ),
  /**
   * La única forma de dejar afuera una pieza que el análisis encontró: DICIÉNDOLO.
   *
   * Medido el 2026-09-22: el análisis listó la lección de escalamiento, una
   * pregunta de la práctica y otra del examen final con el valor viejo, y la
   * nota de la herramienta decía «un ítem edit por cada lección Y por cada
   * ejercicio listado acá». El modelo armó el plan con la sección que el
   * docente había nombrado y nada más. Se aprobó, se construyó, y el curso
   * quedó enseñando el valor nuevo en un lado y el viejo en otro: una nota no
   * es un riel.
   *
   * Hoy el servidor NIEGA un plan de cambios que calle una pieza con
   * ocurrencias. `skip` es la salida legítima —el docente pidió no tocar esa
   * pieza— y el motivo va en `changes`, así que el docente ve en la pantalla
   * qué queda afuera y por qué.
   */
  skip: z
    .boolean()
    .optional()
    .describe(
      'Set true ONLY to declare that this existing piece is deliberately left as it is, with the reason in `changes` (e.g. the teacher asked to leave it alone). The item still needs its target. The server marks it done without measuring it, and the teacher sees it as "left as is".'
    )
});

export const CoursePlanSectionSchema = z.object({
  title: z.string().min(1),
  order: z.number().int().min(0),
  /**
   * La sección del curso a la que pertenece este bloque del plan.
   *
   * Sin esto, un plan de cambios sobre una sección que ya existe sólo podía
   * nombrarla por el título, y el título es justamente lo que el modelo
   * «mejora» mientras trabaja: es de donde salieron las secciones duplicadas
   * (ver `pieza-existente.ts`).
   */
  sectionId: z
    .string()
    .optional()
    .describe(
      'The handle (e.g. S2) or id of the EXISTING course section this block of the plan belongs to. Omit it only when the section itself is new.'
    ),
  items: z
    .array(CoursePlanItemSchema)
    .min(1)
    .describe(
      'Ordered list of lessons and exercises. Use type "exercise" for standalone quizzes (e.g. end-of-section). The final course section’s items must include the comprehensive final examination exercise as specified in the course plan rules.'
    )
});

export const CoursePlanFieldsSchema = z.object({
  title: z.string().min(1),
  /**
   * De qué se trata el plan: del curso entero, o de un cambio sobre uno que ya
   * tiene contenido.
   *
   * Opcional y ausente = `course`, porque los planes ya aprobados que viven en
   * las conversaciones guardadas tienen que seguir parseando: si
   * `getLatestImplementationPlan` deja de reconocerlos, el ancla de progreso
   * desaparece a mitad de una construcción.
   */
  scope: z
    .enum(['course', 'changes'])
    .optional()
    .describe(
      'Leave it out (or "course") for a plan that builds a whole course. Use "changes" when the course already has content and the teacher asked to add, update or rewrite PART of it: then list only the sections you touch, and give every item its action/target/changes. A change plan has no mandatory final exam.'
    ),
  sections: z
    .array(CoursePlanSectionSchema)
    .min(1)
    .describe(
      'Instructional sections in teaching order, then a final section for the comprehensive course examination. The LAST section must hold the final exam (validated when the plan is submitted). Earlier sections cover the curriculum; each prior section should be represented in the exam by its own in-exercise question block with 3–5 questions when the plan is implemented.'
    )
});

/**
 * Validated when calling `generate_course_plan`.
 *
 * Dos reglas, y cuál corre depende del alcance. El examen final obligatorio es
 * de un plan de CURSO: exigirlo en un plan de cambios es lo que convertía
 * «agregá una sección» en el temario entero otra vez. Un plan de cambios tiene
 * su propia regla: un ítem que dice tocar algo existente tiene que decir QUÉ
 * toca y QUÉ le cambia, o no hay nada que el servidor pueda atar ni medir.
 */
export const CoursePlanSchema = CoursePlanFieldsSchema.superRefine((plan, ctx) => {
  if (plan.scope === 'changes') {
    plan.sections.forEach((section, sectionIndex) => {
      section.items.forEach((item, itemIndex) => {
        const action = item.action ?? 'create';

        if (action === 'create') return;

        if (!item.target?.trim()) {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: `A "${action}" item needs \`target\`: the handle (e.g. S2.L3) or id of the existing lesson/exercise it acts on.`,
            path: ['sections', sectionIndex, 'items', itemIndex, 'target']
          });
        }

        if (!item.changes?.trim()) {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: item.skip
              ? 'A `skip` item needs `changes`: the reason you are leaving this piece as it is, so the teacher can see what is left out and why.'
              : `A "${action}" item needs \`changes\`: one or two sentences saying what changes, so the teacher can approve it.`,
            path: ['sections', sectionIndex, 'items', itemIndex, 'changes']
          });
        }
      });

      // `skip` sobre un ítem que se CREA no significa nada: no hay pieza que
      // dejar como está. Aceptarlo sería dejar que un ítem inventado cuente
      // como cobertura de uno real.
      section.items.forEach((item, itemIndex) => {
        if (item.skip && (item.action ?? 'create') === 'create') {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: '`skip` only applies to an existing piece: use action "edit" (or "rewrite") with its target.',
            path: ['sections', sectionIndex, 'items', itemIndex, 'skip']
          });
        }
      });
    });

    return;
  }

  const lastIndex = plan.sections.length - 1;
  const lastSection = plan.sections[lastIndex];
  if (!lastSection) return;

  const hasFinalExamExercise = lastSection.items.some((item) => item.type === 'exercise');
  if (!hasFinalExamExercise) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message:
        'The last section must include at least one exercise item for the comprehensive final examination (in implementation: one exercise with create_exercise_section blocks—one per prior course section—each with 3–5 questions).',
      path: ['sections', lastIndex]
    });
  }
});

export type CoursePlanItem = z.infer<typeof CoursePlanItemSchema>;
export type CoursePlanSection = z.infer<typeof CoursePlanSectionSchema>;
export type CoursePlan = z.infer<typeof CoursePlanFieldsSchema>;
/** Qué se le hace a un ítem del plan. Ausente en el plan = `create`. */
export type CoursePlanItemAction = NonNullable<CoursePlanItem['action']>;

// ─── Tool Names ──────────────────────────────────────────────────────────────

export const ToolName = {
  // Read tools (shared)
  GET_COURSE_STRUCTURE: 'get_course_structure',
  GET_LESSON_CONTENT: 'get_lesson_content',
  GET_EXERCISE_DETAILS: 'get_exercise_details',
  // Write tools (teacher only)
  CREATE_SECTION: 'create_section',
  UPDATE_SECTION: 'update_section',
  CREATE_LESSON: 'create_lesson',
  UPDATE_LESSON: 'update_lesson',
  UPDATE_LESSON_CONTENT: 'update_lesson_content',
  EDIT_LESSON_CONTENT: 'edit_lesson_content',
  REPLACE_LESSON_BLOCK: 'replace_lesson_block',
  CREATE_EXERCISE: 'create_exercise',
  CREATE_EXERCISE_SECTION: 'create_exercise_section',
  UPDATE_EXERCISE: 'update_exercise',
  UPDATE_EXERCISE_SECTION: 'update_exercise_section',
  ADD_QUESTIONS: 'add_questions',
  UPDATE_QUESTIONS: 'update_questions',
  UPDATE_COURSE_LANDING_PAGE: 'update_course_landing_page',
  CHECK_COURSE_GO_LIVE_READINESS: 'check_course_go_live_readiness',
  GO_LIVE_COURSE: 'go_live_course',
  // Agent tools
  GENERATE_COURSE_PLAN: 'generate_course_plan',
  ASK_TEMPLATE_QUESTIONS: 'ask_template_questions',
  ASK_DISCOVERY_QUESTIONS: 'ask_discovery_questions',
  FETCH_DOCUMENTATION_URL: 'fetch_documentation_url',
  GENERATE_IMAGE: 'generate_image',
  // Student read tools (course-scoped, read-only)
  LIST_COURSE_OUTLINE: 'list_course_outline',
  READ_LESSON: 'read_lesson',
  READ_EXERCISE: 'read_exercise',
  SEARCH_COURSE: 'search_course'
} as const;

export type ToolName = (typeof ToolName)[keyof typeof ToolName];

// ─── Token Usage ─────────────────────────────────────────────────────────────

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  /**
   * Optional detailed breakdown (populated when the provider reports it, e.g.
   * Gemini via AI SDK v7). Reasoning is a subset of completionTokens; cacheRead/
   * cacheWrite are subsets of promptTokens (cacheRead is billed at ~10%). Left
   * undefined by callers that only have the coarse totals.
   */
  reasoningTokens?: number;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
}

export interface TokenBalance {
  used: number;
  allowance: number;
  creditBalance: number;
  remaining: number;
}

// ─── Agent Status (returned by GET /agent/status) ────────────────────────────

export interface AgentTutorStatus {
  /** Whether AI tutor is enabled for this workspace. */
  enabled: boolean;
  /** Remaining tutor messages for the current learner this calendar month (only set for students). */
  capRemaining: number | null;
  /** Per-learner monthly cap value (only set for students). */
  cap: number | null;
  /** Whether cap enforcement is on in this environment (Phase 3+). */
  enforced: boolean;
}

export interface AgentStatus {
  enabled: boolean;
  role: AgentRole;
  usage: TokenBalance;
  tutor: AgentTutorStatus;
  /**
   * Operational context budget (tokens) the UI measures usage against for the
   * context indicator and the "context full" compaction prompt. This is NOT the
   * model's physical window (Gemini flash is 1M): it's a budget chosen so the
   * indicator is useful and compaction is offered before per-request cost climbs.
   * Overridable via AGENT_CONTEXT_BUDGET; see DEFAULT_AGENT_CONTEXT_BUDGET.
   */
  contextWindow: number;
  /**
   * Whether this user can attach images to a chat message: course team only, and
   * only when the chat model can see them. The composer hides the control
   * otherwise, instead of accepting an image the model would silently ignore.
   */
  imageInput: boolean;
}

/**
 * Default operational context budget (tokens). Not the model's physical window —
 * a working ceiling for the UI's context guard. At ~90% (180k) the UI nudges the
 * teacher to compact; well under Gemini's 1M so we never actually hit the wall,
 * while keeping the indicator meaningful now that the context diet keeps typical
 * requests small. Override with AGENT_CONTEXT_BUDGET.
 */
export const DEFAULT_AGENT_CONTEXT_BUDGET = 200_000;

/** Resolve the operational context budget from env, falling back to the default. */
export function resolveAgentContextBudget(): number {
  const raw = process.env.AGENT_CONTEXT_BUDGET?.trim();
  if (!raw) return DEFAULT_AGENT_CONTEXT_BUDGET;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : DEFAULT_AGENT_CONTEXT_BUDGET;
}

// ─── Document Upload ─────────────────────────────────────────────────────────

export interface DocumentUploadResult {
  documentId: string;
  fileName: string;
  mimeType: string;
  pageCount: number | null;
  wordCount: number;
  textPreview: string;
  truncated: boolean;
}

// ─── Constants ───────────────────────────────────────────────────────────────

/**
 * Maximum characters of extracted document text kept for LLM context. At 100k a
 * large manual (300+ pages) got silently truncated to its first ~50–70 pages, so the
 * agent planned/wrote the course over a fraction of the source. Gemini's 1M-token
 * window fits far more, so we raise this to ~500k chars (~125k words, ~250–350 pages,
 * ~180k tokens) — big enough for real books while staying under the context region
 * where "lost in the middle" attention decay gets bad. Documents beyond this are still
 * truncated (a warning is surfaced); the map-reduce approach is the next step for those.
 */
export const MAX_DOCUMENT_TEXT_LENGTH = 500_000;

/** Maximum file size for document upload. Raised to 25MB so large PDFs (whose byte
 *  size dwarfs their text) actually upload instead of being rejected before parsing. */
export const MAX_AGENT_DOCUMENT_SIZE = 25 * 1024 * 1024;

/** Redis TTL for uploaded document text (1 hour) */
export const DOCUMENT_REDIS_TTL = 3600;

/**
 * Maximum steps per streamText() round. A full course build (sections + lessons +
 * content + exercises + questions) easily needs 30–50 tool calls; at 15 the agent
 * ran out mid-plan and stopped. 40 lets most courses finish in one round; anything
 * longer is picked up by the step-limit continuation flow.
 */
export const MAX_STEPS_PER_ROUND = 40;

/**
 * The learner-facing tutor answers questions; it does not build anything. Its
 * shape is search → read a lesson or two → answer: three to five steps, and
 * eight even when it is being thorough.
 *
 * The build budget was never meant for it — the caps were simply not per-role.
 * That mattered because every step re-sends the whole prefix, so a tutor stuck
 * in a retry loop (asking `search_course` again and again because the course is
 * only half indexed) could spend ~40 requests on ONE learner question.
 *
 * Set at 12 rather than 8 because this cap is in front of real learners, and the
 * two failure modes are not symmetric: a few unused steps cost nothing, while
 * one truncated answer is a learner told less than the course knows. Twelve is
 * still ~70% off the build budget and roughly triple what a working tutor uses.
 */
export const MAX_STEPS_PER_ROUND_STUDENT = 12;

/**
 * Output ceiling for a learner answer. The tutor's own settings ask for 1–3
 * sentences ("short") up to a structured explanation ("long"); 4096 tokens is
 * roughly 3,000 words, well past the longest of those. The 16k build ceiling
 * exists for turns that emit full lesson HTML for many sections, which the
 * tutor never does — leaving it that high only widens a runaway.
 */
export const MAX_OUTPUT_TOKENS_STUDENT = 4096;

/** Supported MIME types for document upload */
export const SUPPORTED_DOCUMENT_TYPES = [
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation'
] as const;

/** Supported file extensions for document upload */
export const SUPPORTED_DOCUMENT_EXTENSIONS = ['.pdf', '.docx', '.pptx'] as const;

/** Token cost estimation heuristics (tokens per item) */
export const TOKEN_COST_ESTIMATES = {
  SECTION_CREATE: 500,
  LESSON_CREATE_AND_CONTENT: 3000,
  EXERCISE_CREATE: 1500
} as const;
