/**
 * The rules for writing a lesson diagram, in one place.
 *
 * Two callers need them and they must not drift apart: the course builder, which
 * writes diagrams as part of a lesson, and the single-diagram regenerator behind
 * the "improve this diagram" control in the lesson view. When these lived only
 * inside the teacher prompt, fixing a rule in one path silently left the other
 * producing the defect it was meant to stop.
 *
 * Every rule here was written against a defect seen in a real generated lesson,
 * not imagined — see `validateSvgDiagram` in the API, whose checks mirror them.
 */
export const SVG_DIAGRAM_RULES = `- **Sizing (the #1 cause of broken diagrams):** each <svg> renders inside a fixed-size sandboxed box whose height comes from your root \`height\` attribute. **If your content is taller than that height, it gets CLIPPED.** So: set \`viewBox="0 0 W H"\` and make the root \`width="W"\` and \`height="H"\` match that same aspect ratio, and make sure EVERY element (shapes AND text) sits fully inside \`0..W\` × \`0..H\` with ~10px padding from every edge. Never let a label run past the right edge or below the bottom. Recommended canvas: 640–800 wide; height whatever the content needs (don't cram — grow the height instead of overlapping).
- **Text must fit and not overlap:** minimum \`font-size="14"\` (never below 12). Keep labels short. Leave clear vertical space between rows/nodes (≥40px). Do not stack two text elements at nearly the same y. If a label is long, split it across two <text> lines rather than letting it overflow its box.
- **Paint order: ALL shapes first, THEN all text.** SVG paints in document order, so any <rect>/<circle>/<ellipse> written after a <text> covers it. This is what silently truncates labels in Venn diagrams — the intersection ellipse drawn last swallows the set names on either side of it. Emit every filled shape, then every label.
- **Give the caption its own band.** A closing sentence under the figure must sit BELOW everything else, in vertical space nobody else uses: grow the canvas height by ~30px and put the caption there. A caption placed at the same height as the axis labels runs straight through them — a full-width sentence crosses every tick label on the axis, even though each one is in a different column.
- **When a value maps to a position, keep the scale linear.** On an axis, the pixel distance between 0 and 2 must equal the distance between 6 and 8. Compute each x as \`left + (value - min) / (max - min) * plotWidth\` rather than eyeballing it, and put tick labels below the axis line, never inside the plot area.
- **Legibility:** dark text (#1e293b) on light fills; a small readable palette (e.g. #3b82f6 blue, #10b981 green, #f59e0b amber, #ef4444 red, #e2e8f0 light-grey boxes) with #334155 strokes. The box always has a near-white background, so avoid white/very-light text.
- **Structure:** self-contained (no external refs, no <style>, no CSS classes — use presentation attributes like \`fill=\` / \`stroke=\` directly). Do NOT use <foreignObject>. Place each <svg> as its own top-level block, never inside a <p>.
- **No LaTeX in a diagram, ever.** Formulas render through KaTeX, which only walks HTML — SVG \`<text>\` is not HTML and is never visited, so \`\\chi^2_{1-\\alpha/2}\` or \`$\\sigma_0^2$\` inside a label shows as raw source AND overflows the box you sized for the rendered formula. Write symbols directly as Unicode instead: χ² σ₀² σ² α β μ ρ Σ √ ∫ ≤ ≥ ≠ ± ∞ → ×. Keep the label to a short symbol or a plain word, and put the real formula in a block-math span above or below the diagram.
- **One diagram per structure, not one per lesson.** A lesson usually teaches more than one structure: a decision that depends on a condition, a sequence of steps, deadlines on a calendar, who does what. Each gets its own <svg>, placed next to the paragraph that explains it. Two or three diagrams in one lesson is normal. A procedure that has branches AND deadlines is two diagrams, not one row of boxes that carries neither.
- **Pick the shape the content actually has** — the shape is what makes a diagram worth drawing:
  - A **decision** — the rule changes with a condition ("if the document is signed…", "if it exceeds the limit…") → a **decision tree**: each question in its own box, one arrow per answer with the answer written on the arrow, ending in outcome boxes. Draw EVERY branch the material states, the exception included — the exception is usually why the learner needed a diagram at all.
  - A **sequence** → numbered steps left to right, wrapping to a second row instead of shrinking the boxes.
  - **Deadlines or thresholds** ("40 days before", "at 20 days", "on the day") → a **timeline** with each mark at its real position and what happens there.
  - **Who does what** — by role, shift or area → **lanes**: one horizontal band per actor, each step inside the band of whoever does it.
  - A **comparison** — two kinds of something, the right way and the wrong way → **side-by-side columns** with the same rows in each.
- **Complete beats minimal.** Put in every step, condition, actor and number the lesson teaches: a diagram that leaves out the branch the learner gets wrong is decoration. Grow the canvas to fit — taller, or a second row — and never drop content to make it fit. But never draw MORE than the material states: a branch you made up is made-up content, and the text inside a diagram is checked against the sources like the rest of the lesson.
- **Colour by role, the same way every time:** questions amber (#fef3c7); outcomes by result — green (#d1fae5) go ahead, red (#fee2e2) stop or send back, blue (#dbeafe) escalate; plain steps light grey (#e2e8f0).
- **Several diagrams in one lesson:** give each one's arrow marker its own id (\`a\`, \`b\`, \`c\`…), so no two diagrams share one.
- **Worked example — a sequence** (copy the shape, adapt the content):
  \`<svg viewBox="0 0 640 140" width="640" height="140" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="45" width="160" height="50" rx="8" fill="#e2e8f0" stroke="#334155"/><text x="100" y="75" font-size="15" text-anchor="middle" fill="#1e293b">1. Recolectar</text><line x1="180" y1="70" x2="240" y2="70" stroke="#334155" stroke-width="2" marker-end="url(#a)"/><rect x="240" y="45" width="160" height="50" rx="8" fill="#dbeafe" stroke="#334155"/><text x="320" y="75" font-size="15" text-anchor="middle" fill="#1e293b">2. Procesar</text><line x1="400" y1="70" x2="460" y2="70" stroke="#334155" stroke-width="2" marker-end="url(#a)"/><rect x="460" y="45" width="160" height="50" rx="8" fill="#d1fae5" stroke="#334155"/><text x="540" y="75" font-size="15" text-anchor="middle" fill="#1e293b">3. Publicar</text><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#334155"/></marker></defs></svg>\`
- **Worked example — a decision tree** (two questions, three outcomes, the answer on every arrow; copy the shape, adapt the content):
  \`<svg viewBox="0 0 720 320" width="720" height="320" xmlns="http://www.w3.org/2000/svg"><rect x="220" y="16" width="280" height="56" rx="8" fill="#fef3c7" stroke="#334155"/><rect x="20" y="136" width="240" height="52" rx="8" fill="#fee2e2" stroke="#334155"/><rect x="400" y="136" width="300" height="52" rx="8" fill="#fef3c7" stroke="#334155"/><rect x="370" y="256" width="160" height="52" rx="8" fill="#dbeafe" stroke="#334155"/><rect x="550" y="256" width="160" height="52" rx="8" fill="#d1fae5" stroke="#334155"/><line x1="360" y1="72" x2="140" y2="136" stroke="#334155" stroke-width="2" marker-end="url(#b)"/><line x1="360" y1="72" x2="550" y2="136" stroke="#334155" stroke-width="2" marker-end="url(#b)"/><line x1="550" y1="188" x2="450" y2="256" stroke="#334155" stroke-width="2" marker-end="url(#b)"/><line x1="550" y1="188" x2="630" y2="256" stroke="#334155" stroke-width="2" marker-end="url(#b)"/><text x="360" y="49" font-size="15" text-anchor="middle" fill="#1e293b">¿La solicitud está completa?</text><text x="140" y="167" font-size="15" text-anchor="middle" fill="#1e293b">Devolver al solicitante</text><text x="550" y="167" font-size="15" text-anchor="middle" fill="#1e293b">¿Supera el monto autorizado?</text><text x="450" y="287" font-size="15" text-anchor="middle" fill="#1e293b">Aprueba gerencia</text><text x="630" y="287" font-size="15" text-anchor="middle" fill="#1e293b">Aprobar y cargar</text><text x="225" y="96" font-size="14" font-weight="bold" text-anchor="middle" fill="#b91c1c">No</text><text x="470" y="96" font-size="14" font-weight="bold" text-anchor="middle" fill="#047857">Sí</text><text x="484" y="224" font-size="14" font-weight="bold" text-anchor="middle" fill="#047857">Sí</text><text x="612" y="224" font-size="14" font-weight="bold" text-anchor="middle" fill="#b91c1c">No</text><defs><marker id="b" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#334155"/></marker></defs></svg>\``;
